// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Mode démo automatique si Supabase n'est pas configuré
const DEMO_MODE = !SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY || import.meta.env.VITE_DEMO_MODE === 'true';

// En mode démo, créer un client factice pour éviter les erreurs
let supabaseClient;

if (DEMO_MODE) {
  console.log('🧪 MODE DÉMO ACTIVÉ - Supabase désactivé');
  console.log('📌 Pour activer Supabase : configurez VITE_SUPABASE_URL et VITE_SUPABASE_PUBLISHABLE_KEY');

  // Client factice qui ne fait rien
  supabaseClient = createClient('https://demo.supabase.co', 'demo-key-not-real', {
    auth: {
      storage: localStorage,
      persistSession: false,
      autoRefreshToken: false,
    }
  });
} else {
  console.log('✅ Supabase connecté');

  supabaseClient = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    }
  });
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = supabaseClient;